FORMAT: 1A
HOST: https://blacknectar-api.sirwellington.tech:9102/

# BlackNectar API

<img src="https://raw.githubusercontent.com/BlackWholeLabs/BlackNectar-iOS/develop/Design/Logo/Icon-Original.png" width="350"> </img>

The BlackNectar API is a simple API that allows you to view and search 
for Stores in the United States that support EBT (Electronic Benefits Transfer) cards.


# Group Stores


## Search Stores [/stores{?limit,searchTerm,latitude,longitude,radius}]

Search for available EBT Stores.

+ Parameters
    
    + limit (number, optional)      - The maximum number of results to return.
        + Default: 200
    + searchTerm (string, optional) - Searches for stores with this in their names.
    + latitude (number, optional)   - Used in conjunction with `longitude` to specify a location-based search.
    + longitude (number, optional)  - Used in conjunction with `latitude` to specify a location-based search. 
                                      Searches for stores near the specified geo-coordinate.
    + radius (number, optional)     - Defines the radius (in meters) for the geo-query. 
                                      Radius can only be used with `latitude` and `longitude`.


### Search [GET]

Search for Stores using the specified query parameters.


+ Response 200 (application/json)
    + Attributes (array[Store])

+ Response 400 (text/plain)


## Data Structures

### Store
+ store_name: Angelica's Market (string, required) - The name of the Store.
+ address (Address, required)
+ location (Location, required)
+ main_image_url (string, optional) - If present, contains a URL to a picture of the Store.on

### Address
+ address_line_1: 243 E 53rd St (string, required) - The first part of the address.
+ address_line_2: Suite #200 (string, optional) - The second part of the address present on some stores.
+ city: Los Angeles (string, required)
+ state: CA (string, required)
+ county: Los Angeles (string, required)
+ zip_code: `90210` (number, required) - The 5-Digit Zip Code.
+ local_zip_code: 0401 (number, optional) - The Local 4-Digit Zip Code.

### Location
+ latitude: 33.994267 (number, required)
+ longitude: `-118.27029` (number, required)