FORMAT: 1A
HOST: https://blacknectar-api.blacksource.tech:9102/

# BlackNectar API

<img src="https://raw.githubusercontent.com/BlackWholeLabs/BlackNectar-iOS/develop/Design/Logo/Icon-Original.png" width="350"> </img>

The BlackNectar API is a simple API that allows you to view and search 
for Stores in the United States that support EBT (Electronic Benefits Transfer) cards.



<!--Shopping API -->
<!--========================================================-->


# Group Stores


## Search Stores [/stores{?limit,searchTerm,latitude,longitude,radius,zipCode}]

Search for available EBT Stores.

+ Parameters
    
    + limit (number, optional)      - The maximum number of results to return.
        + Default: 200
    + searchTerm (string, optional) - Searches for stores with this in their names.
    + latitude (number, optional)   - Used in conjunction with `longitude` to specify a location-based search.
    + longitude (number, optional)  - Used in conjunction with `latitude` to specify a location-based search. 
                                      Searches for stores near the specified geo-coordinate.
    + radius (number, optional)     - Defines the radius (in meters) for the geo-query. 
                                      Radius can only be used with `latitude` and `longitude`.
    + zipCode (string, optional)    - Searches for store in this Zip Code. This parameter can be used in place of latitude & longitude.
                                      The Radius parameter has no effect on this query.


### Search [GET]

Search for Stores using the specified query parameters.


+ Response 200 (application/json)
    + Attributes (array[Store])

+ Response 400 (text/plain)


## Data Structures

### Store (object)
+ store_id: `5ceaf0fe-cd7b-4ff8-904e-3a6c1be9fbf6` (string, required) - The unique identifier for the Store
+ store_name: `Angelica's Market` (string, required) - The name of the Store.
+ is_farmers_market: false (boolean, required) - Tells whether the store is a Farmer's Market or not.
+ address (Address, required)
+ location (Location, required)
+ main_image_url: `http://www.portagewibid.org/wp-content/uploads/2014/11/Farmersmarket.jpg` (string, optional) - If present, contains a URL to a picture of the Store.

### Address (object)
+ address_line_1: 243 E 53rd St (string, required) - The first part of the address.
+ address_line_2: Suite #200 (string, optional) - The second part of the address present on some stores.
+ city: Los Angeles (string, required)
+ state: CA (string, required)
+ county: Los Angeles (string, required)
+ zip_code: `90210` (number, required) - The 5-Digit Zip Code.
+ local_zip_code: 0401 (number, optional) - The Local 4-Digit Zip Code.

### Location (object)
+ latitude: `33.994267` (number, required)
+ longitude: `-118.27029` (number, required)


<!--EBT API -->
<!--========================================================-->

# Group EBT

Get an EBT Card's Balance and Transaction History.



## API Overview [/ebt]

### Get Supported States [GET]
Get a list of all states supported by the EBT API.

+ Response 200 (application/json)

    + Attributes (array)
    
        + (object) - A State supported by the system
        
            + id: `CA` - The short two-digit code for the state. This is what is used as a path parameter in all API calls
            + name: `California` - The long human-displayable name of the state.



## US State Information [/ebt/{state}]

Information about a particular State. See [#get-supported-states] for details.

+ Parameters
    + state: `NY` (string, required)      - The two-digit abbreviation of the state. Can be upper-case or lower-cased.

### Get State Features and Requirements [GET]
Get a States' features, sign-in requirements, and sign-up requirements.

+ Response 200 (application/json) 
    + Attributes (StateFeatures)

        Get the features available to a particular state

+ Response 404 (application/json) 

        Thrown when acessing a state that does not exist
        
        
        
## Check State Account [/ebt/{state}/check]

### Check State Account Exists [POST]
Check if a user has an account with the state website. The request must include values for each of the required sign-in fields.

+ Request (application/json)
    
    + Attributes (array[FieldValue], required)

+ Response 200 (application/json)
    
    + Attributes (object)
        + exists: `true` (boolean, required) - True if the account exists, false otherwise
        + message (string, optional) - A detailed message in case the operation failed

## Create State Account [/ebt/{state}/create]

### Create Account [POST]
Create an account with the State Website.
Note that each website has different account requirements.

+ Request (application/json)
    + Attributes (array[FieldValue], required)
    
        Values for each of the State's required fields

+ Response 200 (application/json)

    + Attributes (object, required)
        + success: `true` (boolean, required) - Whether the operation succeeded or not
        + message (string, optional) - A detailed message in case the operation failed

## Balance [/ebt/{state}/balance]

### View Balance [POST]
View an EBT Card's Balance. Credentials must be passed into the method body.

+ Request (application/json)
    + Attributes (array[FieldValue], required)
    
        Values necessary to login to the State account

+ Response 200 (application/json)

    + Attributes (object)
        + cash_balance: `93.04` (number, required) - The amount of cash money left on the EBT Card
        + food_balance: `31.30` (number, required) - The amount of food money left on the EBT Card

## Transactions [/ebt/{state}/transactions]

### View Transaction History [POST]
View an EBT Card's Transaction History. Credentials must be passed into the method body.

+ Request (application/json)
    + Attributes (array[FieldValue], required)
        
        Values necessary to login to the State account


+ Response 200 (application/json)
    
    + Attributes (array[Transaction])



## Data Structures

### StateFeatures(object) - An Overview of supported features and requirements for a State

+ sign_in_requirements (array[Field], required) - Fields required in order to sign in
+ sign_up_requirements (array[Field], required) - Fields required in order to create an account
+ features (WebsiteFeature, required) - Features supported by the state


### WebsiteFeature (enum[string])

+ ACCOUNT_CREATION - The state supports the ability to creat an account programmatically.
+ BALANCE - The State supports the "/balance/" api and allows users to get their EBT Balance.
+ TRANSACTION - The State supports the "/transactions/" api and allows users to view their Transaction history.
      


### Field (object)

+ name: `user-id` (string, required) - The unique name of the field. Each field will have a different name.
+ type: `USERNAME` (string, required) - Information about what type of data this field is intended to capture.
+ description: `A unique user ID` (string, optional) - A short human-readable description of the field.
+ is_required: `true` (boolean, required) - Whether this field is required or optional.
+ requirements (StringRequirements, required) - Details any requirements on the value that this field accepts.

### StringRequirements (object)

+ min_length: `4` (number, required) - The value must have at least this many characters
+ max_length: `35` (number, required) - The value cannot have more than this many characters
+ character_requirements (CharacterRequirements, required) - Describes requirements on the characters

### CharacterRequirements (object)

+ requires_lower_case: `true` (boolean, required) - Whether the string requires at least 1 lower case letter
+ requires_upper_case: `false` (boolean, required) - Whether the string requires at least 1 upper case letter
+ requires_number: `true` (boolean, required) - Whether the string requries at least 1 number
+ requires_special_character: `false` (boolean, required) - Whether the string requires at least 1 special character. This is common with Password fields.


### FieldValue (object)

+ name: `user-id` (string, required) - The name of the field. This should be pulled from the Field's `name` parameter.
+ value: `cordhernandez` (string, required) - The value of the field. The value should always be a String.


### Transaction (object)

+ timestamp (object, required) - The timestamp of the transaction
    + seconds: 1474869861 (number, required) - Number of seconds since epoch
    + nanos: `0` (number, optional) - The nanoseconds component
+ amount: `490.20` (number, required) - The amount of the Transaction
+ address: `1000 Santa Monica Blvd Santa Monica, CA` - The address where the Transaction was recorded
+ retailer: `VONS` - The name of the retail company
+ transaction_type: `CHARGE` (enum[string], required)
    + CHARGE
    + DEPOSIT
+ type: `FOOD` (string, required) - Additional information about the type of the transaction.